---
apiVersion: v1
kind: ConfigMap
metadata:
  name: golang-api-configs
  namespace: default
data:
  APP_DB_USERNAME: root
  APP_DB_NAME: testproject
  APP_DB_ADDRESS: mariadb-lb:3306
---
apiVersion: v1
kind: Secret
metadata:
  name: password
data:
 password: bXlwYXNzd29yZA==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - env:
        - name: APP_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: golang-api-configs
              key: APP_DB_USERNAME
        - name: APP_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: golang-api-configs
              key: APP_DB_NAME
        - name: APP_DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: golang-api-configs
              key: APP_DB_ADDRESS
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: password
              key: password
        name: myapp
        image: calinrus/golang-api:1.0
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: password
              key: password
        name: mariadb
        image: calinrus/mariadb:1.0
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
      app: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-lb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
      app: mariadb
