FROM golang:1.11.2-alpine

RUN apk update && \
    apk add git
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/gorilla/mux

WORKDIR /usr/src/app
COPY dockerfiles/golang .

RUN go build -o /usr/local/bin/run_go
RUN rm -rf /usr/src/app

CMD ["/usr/local/bin/run_go"]
